export {
	setZoom,
	handleWheel,
	setMapType,
	setSelectAddress,
	setAddress,
	setCoords,
	setCurrentPointId,
	setPointFields,
	setSwapPoints,
	setDeletePointId,
	setBuildRoute,
	setRouteBuilded,
	setRouteAddresses,
	clearRouteAddresses,
	setRouteTime,
	setRouteLength,
	setChangeRoute,
	setRouteChanged,
	default as mapReducer
} from './map.slice';
