export {
	setZoom,
	handleWheel,
	setMapType,
	setSelectAddress,
	setAddress,
	setCoords,
	setCurrentPointId,
	setSwapPoints,
	setDeletePointId,
	setBuildRoute,
	setRouteBuilded,
	setRouteAddresses,
	clearRouteAddresses,
	setRouteTime,
	setRouteLength,
	setChangeRoute,
	setRouteChanged,
	setPanorama,
	setPanoramaOpen,
	setSearch,
	setSearchValue,
	setBuildSearch,
	setFieldsCount,
	setAzsOnRoute,
	setPointsOnRoute,
	setCenter,
	setFixedCenter,
	setPoints,
	setMapLoading,
	setIsUrlBuid,
	setRouteIsBuilding,
	setIsCursorPoint,
	setCategoryTotals,
	setLocation,
	setCurrentCoords,
	default as mapReducer
} from './map.slice';
